/* ReetFPS - catalogo de comandos do otimizador (dados). Gerado da decompilacao. */
/* 559 comandos unicos. Companheiro de reetfps.c (ver struct Tweak la).        */

#include "reetfps.h"  /* struct Tweak { const char *comando; const char *categoria; } */

/* Desativa servicos do Windows (sc stop/config) para liberar CPU/IO: DiagTrack, SysMain, WSearch, Fax, diagnosticshub, etc. */
const Tweak TWEAKS_SERVICES[] = {
    { "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search\" /v AllowSearchToUseLocation /t REG_DWORD /d 0 /f", "SERVICES" },
    { "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search\" /v AllowSearchToUseLocation /t REG_DWORD /d 1 /f", "SERVICES" },
    { "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\AutoLogger\\AutoLogger-Diagtrack-Listener\" /v Start /t REG_DWORD /d 0 /f", "SERVICES" },
    { "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\diagnosticshub.standardcollector.service\" /v Start /t REG_DWORD /d 4 /f", "SERVICES" },
    { "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\DiagTrack\" /v Start /t REG_DWORD /d 4 /f", "SERVICES" },
    { "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\SysMain\" /v Start /t REG_DWORD /d 2 /f", "SERVICES" },
    { "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\SysMain\" /v Start /t REG_DWORD /d 4 /f", "SERVICES" },
    { "Reg.exe add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Diagnostics\\DiagTrack\" /v \"ShowedToastAtLevel\" /t REG_DWORD /d \"1\" /f", "SERVICES" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search\" /v \"AllowSearchToUseLocation\" /t REG_DWORD /d \"0\" /f", "SERVICES" },
    { "sc config AxInstSV start= demand > nul 2>&1", "SERVICES" },
    { "sc config AxInstSV start= disabled > nul 2>&1", "SERVICES" },
    { "sc config CscService start= demand > nul 2>&1", "SERVICES" },
    { "sc config CscService start= disabled > nul 2>&1", "SERVICES" },
    { "sc config diagnosticshub.standardcollector.service start= demand > nul 2>&1", "SERVICES" },
    { "sc config diagnosticshub.standardcollector.service start= disabled > nul 2>&1", "SERVICES" },
    { "sc config DiagTrack start= auto > nul 2>&1", "SERVICES" },
    { "sc config DiagTrack start= demand > nul 2>&1", "SERVICES" },
    { "sc config DiagTrack start= disabled > nul 2>&1", "SERVICES" },
    { "sc config dmwappushservice start= demand > nul 2>&1", "SERVICES" },
    { "sc config dmwappushservice start= disabled > nul 2>&1", "SERVICES" },
    { "sc config DoSvc start= delayed-auto > nul 2>&1", "SERVICES" },
    { "sc config DoSvc start= demand > nul 2>&1", "SERVICES" },
    { "sc config DoSvc start= disabled > nul 2>&1", "SERVICES" },
    { "sc config Fax start= demand", "SERVICES" },
    { "sc config Fax start= demand > nul 2>&1", "SERVICES" },
    { "sc config Fax start= disabled", "SERVICES" },
    { "sc config Fax start= disabled > nul 2>&1", "SERVICES" },
    { "sc config FontCache start= auto > nul 2>&1", "SERVICES" },
    { "sc config FontCache start= disabled > nul 2>&1", "SERVICES" },
    { "sc config HomeGroupListener start= demand > nul 2>&1", "SERVICES" },
    { "sc config HomeGroupListener start= disabled > nul 2>&1", "SERVICES" },
    { "sc config HomeGroupProvider start= demand > nul 2>&1", "SERVICES" },
    { "sc config HomeGroupProvider start= disabled > nul 2>&1", "SERVICES" },
    { "sc config MapsBroker start= delayed-auto > nul 2>&1", "SERVICES" },
    { "sc config MapsBroker start= demand > nul 2>&1", "SERVICES" },
    { "sc config MapsBroker start= disabled > nul 2>&1", "SERVICES" },
    { "sc config PcaSvc start= auto > nul 2>&1", "SERVICES" },
    { "sc config PcaSvc start= disabled > nul 2>&1", "SERVICES" },
    { "sc config PerfHost start= demand > nul 2>&1", "SERVICES" },
    { "sc config PerfHost start= disabled > nul 2>&1", "SERVICES" },
    { "sc config RetailDemo start= demand > nul 2>&1", "SERVICES" },
    { "sc config RetailDemo start= disabled > nul 2>&1", "SERVICES" },
    { "sc config spooler start= auto > nul 2>&1", "SERVICES" },
    { "sc config spooler start= disabled > nul 2>&1", "SERVICES" },
    { "sc config sppsvc start= delayed-auto > nul 2>&1", "SERVICES" },
    { "sc config sppsvc start= disabled > nul 2>&1", "SERVICES" },
    { "sc config svsvc start= demand > nul 2>&1", "SERVICES" },
    { "sc config svsvc start= disabled > nul 2>&1", "SERVICES" },
    { "sc config SysMain start= auto", "SERVICES" },
    { "sc config SysMain start= auto > nul 2>&1", "SERVICES" },
    { "sc config SysMain start= demand > nul 2>&1", "SERVICES" },
    { "sc config SysMain start= disabled", "SERVICES" },
    { "sc config SysMain start= disabled > nul 2>&1", "SERVICES" },
    { "sc config TrkWks start= auto > nul 2>&1", "SERVICES" },
    { "sc config TrkWks start= disabled > nul 2>&1", "SERVICES" },
    { "sc config UsoSvc start= demand > nul 2>&1", "SERVICES" },
    { "sc config WaaSMedicSvc start= demand > nul 2>&1", "SERVICES" },
    { "sc config WdiServiceHost start= disabled", "SERVICES" },
    { "sc config WerSvc start= demand > nul 2>&1", "SERVICES" },
    { "sc config WerSvc start= disabled > nul 2>&1", "SERVICES" },
    { "sc config wlidsvc start= demand > nul 2>&1", "SERVICES" },
    { "sc config WMPNetworkSvc start= demand > nul 2>&1", "SERVICES" },
    { "sc config WMPNetworkSvc start= disabled > nul 2>&1", "SERVICES" },
    { "sc config WSearch start= delayed-auto > nul 2>&1", "SERVICES" },
    { "sc config WSearch start= disabled > nul 2>&1", "SERVICES" },
    { "sc config wuauserv start= demand > nul 2>&1", "SERVICES" },
    { "sc config wuauserv start= disabled > nul 2>&1", "SERVICES" },
    { "sc stop AxInstSV > nul 2>&1", "SERVICES" },
    { "sc stop CscService > nul 2>&1", "SERVICES" },
    { "sc stop DcpSvc", "SERVICES" },
    { "sc stop diagnosticshub.standardcollector.service", "SERVICES" },
    { "sc stop diagnosticshub.standardcollector.service > nul 2>&1", "SERVICES" },
    { "sc stop DiagTrack", "SERVICES" },
    { "sc stop DiagTrack > nul 2>&1", "SERVICES" },
    { "sc stop dmwappushservice", "SERVICES" },
    { "sc stop dmwappushservice > nul 2>&1", "SERVICES" },
    { "sc stop DoSvc > nul 2>&1", "SERVICES" },
    { "sc stop Fax", "SERVICES" },
    { "sc stop Fax > nul 2>&1", "SERVICES" },
    { "sc stop FontCache > nul 2>&1", "SERVICES" },
    { "sc stop HomeGroupListener > nul 2>&1", "SERVICES" },
    { "sc stop HomeGroupProvider > nul 2>&1", "SERVICES" },
    { "sc stop MapsBroker > nul 2>&1", "SERVICES" },
    { "sc stop PcaSvc > nul 2>&1", "SERVICES" },
    { "sc stop PerfHost > nul 2>&1", "SERVICES" },
    { "sc stop RetailDemo > nul 2>&1", "SERVICES" },
    { "sc stop spooler > nul 2>&1", "SERVICES" },
    { "sc stop sppsvc > nul 2>&1", "SERVICES" },
    { "sc stop svsvc > nul 2>&1", "SERVICES" },
    { "sc stop SysMain", "SERVICES" },
    { "sc stop SysMain > nul 2>&1", "SERVICES" },
    { "sc stop TrkWks > nul 2>&1", "SERVICES" },
    { "sc stop WdiServiceHost", "SERVICES" },
    { "sc stop wercplsupport > nul 2>&1", "SERVICES" },
    { "sc stop WerSvc > nul 2>&1", "SERVICES" },
    { "sc stop WMPNetworkSvc > nul 2>&1", "SERVICES" },
    { "sc stop WSearch > nul 2>&1", "SERVICES" },
    { "sc stop wuauserv > nul 2>&1", "SERVICES" },
};
const int TWEAKS_SERVICES_N = 98;

/* Prioridade de CPU/GPU para jogos: SystemProfile\Tasks\Games (GPU Priority, Priority), Win32PrioritySeparation, SystemResponsiveness, LargeSystemCache. */
const Tweak TWEAKS_CPU_GPU_PRIORITY[] = {
    { "reg add \"HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\" /v \"SystemResponsiveness\" /t REG_DWORD /d 0 /f", "CPU_GPU_PRIORITY" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\" /v \"SystemResponsiveness\" /t REG_DWORD /d 20 /f", "CPU_GPU_PRIORITY" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\" /v SystemResponsiveness /t REG_DWORD /d 10 /f >nul 2>&1", "CPU_GPU_PRIORITY" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games\" /v \"GPU Priority\" /t REG_DWORD /d 8 /f", "CPU_GPU_PRIORITY" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games\" /v \"Priority\" /t REG_DWORD /d 6 /f", "CPU_GPU_PRIORITY" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games\" /v GPU Priority /t REG_DWORD /d 8 /f >nul 2>&1", "CPU_GPU_PRIORITY" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games\" /v Priority /t REG_DWORD /d 6 /f >nul 2>&1", "CPU_GPU_PRIORITY" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management\" /v \"FeatureSettingsOverride\" /t REG_DWORD /d \"3\" /f", "CPU_GPU_PRIORITY" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management\" /v \"FeatureSettingsOverrideMask\" /t REG_DWORD /d \"3\" /f", "CPU_GPU_PRIORITY" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management\" /v LargeSystemCache /t REG_DWORD /d 0 /f", "CPU_GPU_PRIORITY" },
    { "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\PriorityControl\" /v \"Win32PrioritySeparation\" /t REG_DWORD /d 18 /f", "CPU_GPU_PRIORITY" },
    { "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management\\PrefetchParameters\" /v EnablePrefetcher /t REG_DWORD /d 0 /f", "CPU_GPU_PRIORITY" },
    { "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management\\PrefetchParameters\" /v EnablePrefetcher /t REG_DWORD /d 1 /f", "CPU_GPU_PRIORITY" },
    { "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management\\PrefetchParameters\" /v EnableSuperfetch /t REG_DWORD /d 0 /f", "CPU_GPU_PRIORITY" },
    { "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management\\PrefetchParameters\" /v EnableSuperfetch /t REG_DWORD /d 1 /f", "CPU_GPU_PRIORITY" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\" /v \"SystemResponsiveness\" /t REG_DWORD /d \"0\" /f", "CPU_GPU_PRIORITY" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games\" /v \"Affinity\" /t REG_DWORD /d \"0\" /f", "CPU_GPU_PRIORITY" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games\" /v \"Background Only\" /t REG_SZ /d \"False\" /f", "CPU_GPU_PRIORITY" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games\" /v \"BackgroundPriority\" /t REG_DWORD /d \"0\" /f", "CPU_GPU_PRIORITY" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games\" /v \"Clock Rate\" /t REG_DWORD /d \"10000\" /f", "CPU_GPU_PRIORITY" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games\" /v \"GPU Priority\" /t REG_DWORD /d \"8\" /f", "CPU_GPU_PRIORITY" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games\" /v \"Latency Sensitive\" /t REG_SZ /d \"True\" /f", "CPU_GPU_PRIORITY" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games\" /v \"Priority\" /t REG_DWORD /d \"2\" /f", "CPU_GPU_PRIORITY" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games\" /v \"Scheduling Category\" /t REG_SZ /d \"High\" /f", "CPU_GPU_PRIORITY" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games\" /v \"SFIO Priority\" /t REG_SZ /d \"High\" /f", "CPU_GPU_PRIORITY" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Low Latency\" /v \"Affinity\" /t REG_DWORD /d \"0\" /f", "CPU_GPU_PRIORITY" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Low Latency\" /v \"Background Only\" /t REG_SZ /d \"False\" /f", "CPU_GPU_PRIORITY" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Low Latency\" /v \"BackgroundPriority\" /t REG_DWORD /d \"0\" /f", "CPU_GPU_PRIORITY" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Low Latency\" /v \"Clock Rate\" /t REG_DWORD /d \"10000\" /f", "CPU_GPU_PRIORITY" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Low Latency\" /v \"GPU Priority\" /t REG_DWORD /d \"8\" /f", "CPU_GPU_PRIORITY" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Low Latency\" /v \"Latency Sensitive\" /t REG_SZ /d \"True\" /f", "CPU_GPU_PRIORITY" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Low Latency\" /v \"Priority\" /t REG_DWORD /d \"2\" /f", "CPU_GPU_PRIORITY" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Low Latency\" /v \"Scheduling Category\" /t REG_SZ /d \"Medium\" /f", "CPU_GPU_PRIORITY" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Low Latency\" /v \"SFIO Priority\" /t REG_SZ /d \"High\" /f", "CPU_GPU_PRIORITY" },
    { "Reg.exe add \"HKLM\\SYSTEM\\ControlSet001\\Control\\PriorityControl\" /v \"IRQ16Priority\" /t REG_DWORD /d \"2\" /f", "CPU_GPU_PRIORITY" },
    { "Reg.exe add \"HKLM\\SYSTEM\\ControlSet001\\Control\\PriorityControl\" /v \"IRQ8Priority\" /t REG_DWORD /d \"1\" /f", "CPU_GPU_PRIORITY" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\PriorityControl\" /v \"IRQ16Priority\" /t REG_DWORD /d \"2\" /f", "CPU_GPU_PRIORITY" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\PriorityControl\" /v \"IRQ8Priority\" /t REG_DWORD /d \"1\" /f", "CPU_GPU_PRIORITY" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\PriorityControl\" /v \"Win32PrioritySeparation\" /t REG_DWORD /d \"38\" /f", "CPU_GPU_PRIORITY" },
};
const int TWEAKS_CPU_GPU_PRIORITY_N = 39;

/* Responsividade da interface: MenuShowDelay, animacoes do DWM, efeitos visuais. */
const Tweak TWEAKS_UI_RESPONSIVENESS[] = {
    { "reg add \"HKCU\\Control Panel\\Desktop\" /v ForegroundLockTimeout /t REG_DWORD /d 0 /f", "UI_RESPONSIVENESS" },
    { "reg add \"HKCU\\Control Panel\\Desktop\" /v HungAppTimeout /t REG_SZ /d 2000 /f", "UI_RESPONSIVENESS" },
    { "reg add \"HKCU\\Control Panel\\Desktop\" /v HungAppTimeout /t REG_SZ /d 5000 /f", "UI_RESPONSIVENESS" },
    { "reg add \"HKCU\\Control Panel\\Desktop\" /v LowLevelHooksTimeout /t REG_SZ /d 2000 /f", "UI_RESPONSIVENESS" },
    { "reg add \"HKCU\\Control Panel\\Desktop\" /v LowLevelHooksTimeout /t REG_SZ /d 20000 /f", "UI_RESPONSIVENESS" },
    { "reg add \"HKCU\\Control Panel\\Desktop\" /v MenuShowDelay /t REG_SZ /d 0 /f", "UI_RESPONSIVENESS" },
    { "reg add \"HKCU\\Control Panel\\Desktop\" /v MenuShowDelay /t REG_SZ /d 20 /f", "UI_RESPONSIVENESS" },
    { "reg add \"HKCU\\Control Panel\\Desktop\" /v MenuShowDelay /t REG_SZ /d 400 /f", "UI_RESPONSIVENESS" },
    { "reg add \"HKCU\\Control Panel\\Desktop\" /v WaitToKillAppTimeout /t REG_SZ /d 2000 /f", "UI_RESPONSIVENESS" },
    { "reg add \"HKCU\\Control Panel\\Desktop\" /v WaitToKillAppTimeout /t REG_SZ /d 20000 /f", "UI_RESPONSIVENESS" },
    { "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\VisualEffects\" /v VisualFXSetting /t REG_DWORD /d 0 /f", "UI_RESPONSIVENESS" },
    { "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\VisualEffects\" /v VisualFXSetting /t REG_DWORD /d 2 /f", "UI_RESPONSIVENESS" },
    { "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\VisualEffects\" /v VisualFXSettingPerUser /t REG_DWORD /d 0 /f", "UI_RESPONSIVENESS" },
    { "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\VisualEffects\" /v VisualFXSettingPerUser /t REG_DWORD /d 2 /f", "UI_RESPONSIVENESS" },
    { "reg add \"HKCU\\Software\\Microsoft\\Windows\\DWM\" /v AccentColor /t REG_DWORD /d 0x00000000 /f", "UI_RESPONSIVENESS" },
    { "reg add \"HKCU\\Software\\Microsoft\\Windows\\DWM\" /v AccentColor /t REG_DWORD /d 0xFFFFFFFF /f", "UI_RESPONSIVENESS" },
    { "reg add \"HKCU\\SOFTWARE\\Microsoft\\Windows\\DWM\" /v AlwaysHibernateThumbnails /t REG_DWORD /d 0 /f", "UI_RESPONSIVENESS" },
    { "reg add \"HKCU\\SOFTWARE\\Microsoft\\Windows\\DWM\" /v AlwaysHibernateThumbnails /t REG_DWORD /d 1 /f", "UI_RESPONSIVENESS" },
    { "reg add \"HKCU\\Software\\Microsoft\\Windows\\DWM\" /v ColorPrevalence /t REG_DWORD /d 0 /f", "UI_RESPONSIVENESS" },
    { "reg add \"HKCU\\Software\\Microsoft\\Windows\\DWM\" /v ColorPrevalence /t REG_DWORD /d 1 /f", "UI_RESPONSIVENESS" },
    { "reg add \"HKEY_CURRENT_USER\\Control Panel\\Desktop\" /v DockMoving /t REG_SZ /d 0 /f", "UI_RESPONSIVENESS" },
    { "reg add \"HKEY_CURRENT_USER\\Control Panel\\Desktop\" /v DockMoving /t REG_SZ /d 1 /f", "UI_RESPONSIVENESS" },
    { "reg add \"HKEY_CURRENT_USER\\Control Panel\\Desktop\" /v MenuShowDelay /t REG_SZ /d 0 /f", "UI_RESPONSIVENESS" },
    { "reg add \"HKEY_CURRENT_USER\\Control Panel\\Desktop\" /v MenuShowDelay /t REG_SZ /d 0 /f >nul 2>&1", "UI_RESPONSIVENESS" },
    { "reg add \"HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Windows\\DWM\" /v ColorPrevalence /t REG_DWORD /d 0 /f", "UI_RESPONSIVENESS" },
    { "reg add \"HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Windows\\DWM\" /v ColorPrevalence /t REG_DWORD /d 1 /f", "UI_RESPONSIVENESS" },
    { "reg add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\DWM\" /v DisableAnimations /t REG_DWORD /d 1 /f >nul 2>&1", "UI_RESPONSIVENESS" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\Dwm\" /v OverlayTestMode /t REG_DWORD /d 5 /f", "UI_RESPONSIVENESS" },
    { "Reg.exe add \"HKCU\\Control Panel\\Desktop\" /v \"AutoEndTasks\" /t REG_SZ /d \"1\" /f", "UI_RESPONSIVENESS" },
    { "Reg.exe add \"HKCU\\Control Panel\\Desktop\" /v \"HungAppTimeout\" /t REG_SZ /d \"1000\" /f", "UI_RESPONSIVENESS" },
    { "Reg.exe add \"HKCU\\Control Panel\\Desktop\" /v \"LowLevelHooksTimeout\" /t REG_SZ /d \"1000\" /f", "UI_RESPONSIVENESS" },
    { "Reg.exe add \"HKCU\\Control Panel\\Desktop\" /v \"MenuShowDelay\" /t REG_SZ /d \"0\" /f", "UI_RESPONSIVENESS" },
    { "Reg.exe add \"HKCU\\Control Panel\\Desktop\" /v \"WaitToKillAppTimeout\" /t REG_SZ /d \"1000\" /f", "UI_RESPONSIVENESS" },
};
const int TWEAKS_UI_RESPONSIVENESS_N = 33;

/* Planos de energia via powercfg (SCHEME_MIN/BALANCED, PERFBOOSTMODE/POL, throttle, timeouts, hibernate). */
const Tweak TWEAKS_POWER[] = {
    { "/C powercfg -import \"", "POWER" },
    { "/C powercfg -setactive", "POWER" },
    { "cmd.exe /C powercfg /query %s", "POWER" },
    { "powercfg -setactive SCHEME_BALANCED", "POWER" },
    { "powercfg -setactive SCHEME_MIN", "POWER" },
    { "powercfg -setacvalueindex SCHEME_BALANCED SUB_PROCESSOR PERFBOOSTMODE 1", "POWER" },
    { "powercfg -setacvalueindex SCHEME_BALANCED SUB_PROCESSOR PERFBOOSTPOL 100", "POWER" },
    { "powercfg -setacvalueindex SCHEME_BALANCED SUB_PROCESSOR PERFINCTHRESHOLD 50", "POWER" },
    { "powercfg -setacvalueindex SCHEME_BALANCED SUB_PROCESSOR PROCTHROTTLEMAX 100", "POWER" },
    { "powercfg -setacvalueindex SCHEME_MIN SUB_PROCESSOR PERFBOOSTMODE 0", "POWER" },
    { "powercfg -setacvalueindex SCHEME_MIN SUB_PROCESSOR PERFBOOSTPOL 100", "POWER" },
    { "powercfg -setacvalueindex SCHEME_MIN SUB_PROCESSOR PERFINCTHRESHOLD 100", "POWER" },
    { "powercfg -setacvalueindex SCHEME_MIN SUB_PROCESSOR PROCTHROTTLEMAX 100", "POWER" },
    { "powercfg -setdcvalueindex SCHEME_BALANCED SUB_PROCESSOR PERFBOOSTMODE 1", "POWER" },
    { "powercfg -setdcvalueindex SCHEME_BALANCED SUB_PROCESSOR PERFBOOSTPOL 100", "POWER" },
    { "powercfg -setdcvalueindex SCHEME_BALANCED SUB_PROCESSOR PERFINCTHRESHOLD 50", "POWER" },
    { "powercfg -setdcvalueindex SCHEME_BALANCED SUB_PROCESSOR PROCTHROTTLEMAX 100", "POWER" },
    { "powercfg -setdcvalueindex SCHEME_MIN SUB_PROCESSOR PERFBOOSTMODE 0", "POWER" },
    { "powercfg -setdcvalueindex SCHEME_MIN SUB_PROCESSOR PERFBOOSTPOL 100", "POWER" },
    { "powercfg -setdcvalueindex SCHEME_MIN SUB_PROCESSOR PERFINCTHRESHOLD 100", "POWER" },
    { "powercfg -setdcvalueindex SCHEME_MIN SUB_PROCESSOR PROCTHROTTLEMAX 100", "POWER" },
    { "powercfg /change disk-timeout-ac 0 >nul 2>&1", "POWER" },
    { "powercfg /change lidclose-action nothing >nul 2>&1", "POWER" },
    { "powercfg /change standby-timeout-ac 0 >nul 2>&1", "POWER" },
    { "powercfg /hibernate off", "POWER" },
    { "powercfg /hibernate off >nul 2>&1", "POWER" },
    { "powercfg /hibernate on", "POWER" },
    { "powercfg /setactive SCHEME_MIN >nul 2>&1", "POWER" },
};
const int TWEAKS_POWER_N = 28;

/* Desativa GameDVR/GameBar e captura de video/audio/cursor do Windows. */
const Tweak TWEAKS_GAMEDVR_GAMEBAR[] = {
    { "reg add \"HKCU\\Software\\Microsoft\\GameBar\" /v \"AllowAutoGameMode\" /t REG_DWORD /d 0 /f", "GAMEDVR_GAMEBAR" },
    { "reg add \"HKCU\\Software\\Microsoft\\GameBar\" /v \"AllowAutoGameMode\" /t REG_DWORD /d 1 /f", "GAMEDVR_GAMEBAR" },
    { "reg add \"HKCU\\Software\\Microsoft\\GameBar\" /v \"UseNexusForGameBarEnabled\" /t REG_DWORD /d 0 /f", "GAMEDVR_GAMEBAR" },
    { "reg add \"HKCU\\Software\\Microsoft\\GameBar\" /v \"UseNexusForGameBarEnabled\" /t REG_DWORD /d 1 /f", "GAMEDVR_GAMEBAR" },
    { "reg add \"HKCU\\System\\GameConfigStore\" /v \"GameMode\" /t REG_DWORD /d 0 /f", "GAMEDVR_GAMEBAR" },
    { "reg add \"HKCU\\System\\GameConfigStore\" /v \"GameMode\" /t REG_DWORD /d 1 /f", "GAMEDVR_GAMEBAR" },
    { "reg add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\GameDVR\" /v \"AppCaptureEnabled\" /t REG_DWORD /d 0 /f", "GAMEDVR_GAMEBAR" },
    { "reg add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\GameDVR\" /v \"AppCaptureEnabled\" /t REG_DWORD /d 1 /f", "GAMEDVR_GAMEBAR" },
    { "reg add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\GameDVR\" /v \"AudioCaptureEnabled\" /t REG_DWORD /d 0 /f", "GAMEDVR_GAMEBAR" },
    { "reg add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\GameDVR\" /v \"AudioCaptureEnabled\" /t REG_DWORD /d 1 /f", "GAMEDVR_GAMEBAR" },
    { "reg add \"HKEY_CURRENT_USER\\System\\GameConfigStore\" /v \"GameDVR_Enabled\" /t REG_DWORD /d 0 /f", "GAMEDVR_GAMEBAR" },
    { "reg add \"HKEY_CURRENT_USER\\System\\GameConfigStore\" /v \"GameDVR_Enabled\" /t REG_DWORD /d 1 /f", "GAMEDVR_GAMEBAR" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\PolicyManager\\default\\ApplicationManagement\\AllowGameDVR\" /v \"value\" /t REG_DWORD /d 0 /f", "GAMEDVR_GAMEBAR" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\PolicyManager\\default\\ApplicationManagement\\AllowGameDVR\" /v \"value\" /t REG_DWORD /d 1 /f", "GAMEDVR_GAMEBAR" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\GameBar\" /v \"GameDVR_Enabled\" /t REG_DWORD /d \"0\" /f", "GAMEDVR_GAMEBAR" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\GameBar\" /v \"UseNexusForGameBarEnabled\" /t REG_DWORD /d \"0\" /f", "GAMEDVR_GAMEBAR" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\GameDVR\" /v \"AppCaptureEnabled\" /t REG_DWORD /d \"0\" /f", "GAMEDVR_GAMEBAR" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\GameDVR\" /v \"AudioCaptureEnabled\" /t REG_DWORD /d \"0\" /f", "GAMEDVR_GAMEBAR" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\GameDVR\" /v \"CursorCaptureEnabled\" /t REG_DWORD /d \"0\" /f", "GAMEDVR_GAMEBAR" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\GameDVR\" /v \"HistoricalCaptureEnabled\" /t REG_DWORD /d \"0\" /f", "GAMEDVR_GAMEBAR" },
    { "Reg.exe add \"HKCU\\System\\GameConfigStore\" /v \"GameDVR_Enabled\" /t REG_DWORD /d \"0\" /f", "GAMEDVR_GAMEBAR" },
    { "Reg.exe add \"HKLM\\Software\\Policies\\Microsoft\\Windows\\GameDVR\" /v \"AllowgameDVR\" /t REG_DWORD /d \"0\" /f", "GAMEDVR_GAMEBAR" },
};
const int TWEAKS_GAMEDVR_GAMEBAR_N = 22;

/* Ajustes de rede: parametros Tcpip, TCPNoDelay, NetworkThrottlingIndex, RSS, netsh. */
const Tweak TWEAKS_NETWORK[] = {
    { "netsh int tcp set global rss=enabled >nul 2>&1", "NETWORK" },
    { "netsh interface set interface \"", "NETWORK" },
    { "netsh.exe", "NETWORK" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters\" /v \"TcpAckFrequency\" /t REG_DWORD /d 1 /f", "NETWORK" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters\" /v \"TCPNoDelay\" /t REG_DWORD /d 1 /f", "NETWORK" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters\" /v MaxUserPort /t REG_DWORD /d 65534 /f >nul 2>&1", "NETWORK" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters\" /v Tcp1323Opts /t REG_DWORD /d 1 /f >nul 2>&1", "NETWORK" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters\" /v TCPNoDelay /t REG_DWORD /d 1 /f >nul 2>&1", "NETWORK" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters\" /v TcpTimedWaitDelay /t REG_DWORD /d 30 /f >nul 2>&1", "NETWORK" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\TCPIPLOGGER\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "NETWORK" },
};
const int TWEAKS_NETWORK_N = 10;

/* Privacidade/telemetria: AllowTelemetry=0, DataCollection, DiagTrack. */
const Tweak TWEAKS_PRIVACY_TELEMETRY[] = {
    { "reg add \"HKCU\\Software\\Microsoft\\Office\\16.0\\Common\\Telemetry\" /v DisableLogging /t REG_DWORD /d 0 /f", "PRIVACY_TELEMETRY" },
    { "reg add \"HKCU\\Software\\Microsoft\\Office\\16.0\\Common\\Telemetry\" /v DisableLogging /t REG_DWORD /d 1 /f", "PRIVACY_TELEMETRY" },
    { "reg add \"HKCU\\Software\\Microsoft\\Office\\16.0\\Common\\Telemetry\" /v DisableTelemetry /t REG_DWORD /d 0 /f", "PRIVACY_TELEMETRY" },
    { "reg add \"HKCU\\Software\\Microsoft\\Office\\16.0\\Common\\Telemetry\" /v DisableTelemetry /t REG_DWORD /d 1 /f", "PRIVACY_TELEMETRY" },
    { "reg add \"HKCU\\Software\\Policies\\Microsoft\\Office\\16.0\\Common\\Telemetry\" /v EnableTelemetry /t REG_DWORD /d 0 /f", "PRIVACY_TELEMETRY" },
    { "reg add \"HKCU\\Software\\Policies\\Microsoft\\Office\\16.0\\Common\\Telemetry\" /v EnableTelemetry /t REG_DWORD /d 1 /f", "PRIVACY_TELEMETRY" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\DataCollection\" /v AllowTelemetry /t REG_DWORD /d 0 /f >nul 2>&1", "PRIVACY_TELEMETRY" },
    { "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\DataCollection\" /v AllowTelemetry /t REG_DWORD /d 0 /f", "PRIVACY_TELEMETRY" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Office\\Common\\ClientTelemetry\" /v \"DisableTelemetry\" /t REG_DWORD /d \"1\" /f", "PRIVACY_TELEMETRY" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Office\\Common\\ClientTelemetry\" /v \"SendTelemetry\" /t REG_DWORD /d \"3\" /f", "PRIVACY_TELEMETRY" },
};
const int TWEAKS_PRIVACY_TELEMETRY_N = 10;

/* Remove pacotes appx do Windows (ex.: Cortana) e permite reinstalar. */
const Tweak TWEAKS_APPX_REMOVE[] = {
    { "Get-AppxPackage -Name $n | Remove-AppxPackage -ErrorAction Stop; 'OK|' + $n", "APPX_REMOVE" },
    { "PowerShell -Command \"Get-AppxPackage -allusers Microsoft.549981C3F5F10 | Remove-AppxPackage\"", "APPX_REMOVE" },
    { "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search\" /v AllowCortana /t REG_DWORD /d 0 /f", "APPX_REMOVE" },
    { "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search\" /v AllowCortana /t REG_DWORD /d 1 /f", "APPX_REMOVE" },
    { "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search\" /v AllowCortanaAboveLock /t REG_DWORD /d 0 /f", "APPX_REMOVE" },
    { "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search\" /v AllowCortanaAboveLock /t REG_DWORD /d 1 /f", "APPX_REMOVE" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search\" /v \"AllowCortana\" /t REG_DWORD /d \"0\" /f", "APPX_REMOVE" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search\" /v \"AllowCortanaAboveLock\" /t REG_DWORD /d \"0\" /f", "APPX_REMOVE" },
};
const int TWEAKS_APPX_REMOVE_N = 8;

/* Parametros de boot via bcdedit (useplatformtick, tscsyncpolicy, hypervisorlaunchtype, numproc, truncatememory). */
const Tweak TWEAKS_BOOT_BCDEDIT[] = {
    { "bcdedit /deletevalue numproc >nul 2>&1", "BOOT_BCDEDIT" },
    { "bcdedit /deletevalue truncatememory >nul 2>&1", "BOOT_BCDEDIT" },
    { "bcdedit /set hypervisorlaunchtype off >nul 2>&1", "BOOT_BCDEDIT" },
    { "bcdedit /set tscsyncpolicy Enhanced >nul 2>&1", "BOOT_BCDEDIT" },
    { "bcdedit /set useplatformtick yes >nul 2>&1", "BOOT_BCDEDIT" },
    { "bcdedit.exe", "BOOT_BCDEDIT" },
};
const int TWEAKS_BOOT_BCDEDIT_N = 6;

/* Limita o tamanho maximo dos logs de eventos (Application/Security/System). */
const Tweak TWEAKS_EVENTLOG[] = {
    { "reg add \"HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\EventLog\\Application\" /v MaxSize /t REG_DWORD /d 1048576 /f >nul 2>&1", "EVENTLOG" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\EventLog\\Security\" /v MaxSize /t REG_DWORD /d 1048576 /f >nul 2>&1", "EVENTLOG" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\EventLog\\System\" /v MaxSize /t REG_DWORD /d 1048576 /f >nul 2>&1", "EVENTLOG" },
};
const int TWEAKS_EVENTLOG_N = 3;

/* Diversos: mouse/teclado (Control Panel\Mouse, Accessibility), menu de contexto do proprio ReetFPS, e demais reg add nao classificados acima. Inclui pares aplicar/reverter. */
const Tweak TWEAKS_OTHER[] = {
    { "reg add \"HKCR\\directory\\background\\shell\\ReetFPS - Optimizer\" /v \"Icon\" /t REG_EXPAND_SZ /d \"C:\\ReetFPS - Optimizer\\ReetFPS.exe\" /f", "OTHER" },
    { "reg add \"HKCR\\directory\\background\\shell\\ReetFPS - Optimizer\\command\" /ve /t REG_SZ /d \"C:\\ReetFPS - Optimizer\\ReetFPS.exe\" /f", "OTHER" },
    { "reg add \"HKCU\\Control Panel\\Accessibility\\Keyboard Response\" /v AutoRepeatDelay /t REG_SZ /d 250 /f", "OTHER" },
    { "reg add \"HKCU\\Control Panel\\Accessibility\\Keyboard Response\" /v AutoRepeatDelay /t REG_SZ /d 300 /f", "OTHER" },
    { "reg add \"HKCU\\Control Panel\\Accessibility\\Keyboard Response\" /v AutoRepeatRate /t REG_SZ /d 20 /f", "OTHER" },
    { "reg add \"HKCU\\Control Panel\\Accessibility\\Keyboard Response\" /v AutoRepeatRate /t REG_SZ /d 45 /f", "OTHER" },
    { "reg add \"HKCU\\Control Panel\\Accessibility\\Keyboard Response\" /v BounceTime /t REG_SZ /d 0 /f", "OTHER" },
    { "reg add \"HKCU\\Control Panel\\Accessibility\\Keyboard Response\" /v Flags /t REG_SZ /d 0 /f >nul 2>&1", "OTHER" },
    { "reg add \"HKCU\\Control Panel\\Accessibility\\Keyboard Response\" /v Flags /t REG_SZ /d 2 /f", "OTHER" },
    { "reg add \"HKCU\\Control Panel\\Accessibility\\MouseKeys\" /v Flags /t REG_SZ /d 0 /f >nul 2>&1", "OTHER" },
    { "reg add \"HKCU\\Control Panel\\Mouse\" /v DoubleClickSpeed /t REG_SZ /d 0 /f", "OTHER" },
    { "reg add \"HKCU\\Control Panel\\Mouse\" /v MouseHoverTime /t REG_SZ /d 0 /f", "OTHER" },
    { "reg add \"HKCU\\Control Panel\\Mouse\" /v MouseHoverTime /t REG_SZ /d 20 /f", "OTHER" },
    { "reg add \"HKCU\\Control Panel\\Mouse\" /v MouseHoverTime /t REG_SZ /d 400 /f", "OTHER" },
    { "reg add \"HKCU\\Control Panel\\Mouse\" /v MouseSensitivity /t REG_SZ /d 10 /f", "OTHER" },
    { "reg add \"HKCU\\Control Panel\\Mouse\" /v MouseSonar /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKCU\\Control Panel\\Mouse\" /v MouseSpeed /t REG_SZ /d 0 /f", "OTHER" },
    { "reg add \"HKCU\\Control Panel\\Mouse\" /v MouseThreshold1 /t REG_SZ /d 0 /f", "OTHER" },
    { "reg add \"HKCU\\Control Panel\\Mouse\" /v MouseThreshold2 /t REG_SZ /d 0 /f", "OTHER" },
    { "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\BackgroundAccessApplications\" /v GlobalUserDisabled /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\BackgroundAccessApplications\" /v GlobalUserDisabled /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\BackgroundAccessApplications\\AppInfo\" /v BackgroundTaskHost.exe /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\BackgroundAccessApplications\\AppInfo\" /v BackgroundTransferHost.exe /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\BackgroundAccessApplications\\AppInfo\" /v cloudexperiencehost.exe /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\BackgroundAccessApplications\\AppInfo\" /v LockApp.exe /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\PushNotifications\" /v ToastEnabled /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\PushNotifications\" /v ToastEnabled /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Search\" /v BackgroundAppGlobalToggle /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Search\" /v BackgroundAppGlobalToggle /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize\" /v AppsUseLightTheme /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize\" /v AppsUseLightTheme /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize\" /v SystemUsesLightTheme /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize\" /v SystemUsesLightTheme /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKCU\\Software\\Policies\\Microsoft\\Office\\16.0\\Common\\Feedback\" /v EnableCustomerExperienceImprovementProgram /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKCU\\Software\\Policies\\Microsoft\\Office\\16.0\\Common\\Feedback\" /v EnableCustomerExperienceImprovementProgram /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKCU\\Software\\Policies\\Microsoft\\Office\\16.0\\Common\\Feedback\" /v EnableFeedback /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKCU\\Software\\Policies\\Microsoft\\Office\\16.0\\Common\\Feedback\" /v EnableFeedback /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKCU\\Software\\Policies\\Microsoft\\Windows\\Explorer\" /v DisableNotificationCenter /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKCU\\Software\\Policies\\Microsoft\\Windows\\Explorer\" /v DisableNotifications /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\Control Panel\\Mouse\" /v MouseHoverTime /t REG_SZ /d 0 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager\" /v ContentDeliveryAllowed /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager\" /v FeatureManagementEnabled /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager\" /v PreInstalledAppsEverEnabled /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager\" /v SilentInstalledAppsEnabled /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager\" /v SoftLandingEnabled /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager\" /v SubscribedContent-310093Enabled /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager\" /v SubscribedContent-314559Enabled /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager\" /v SubscribedContent-338387Enabled /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager\" /v SubscribedContent-338388Enabled /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager\" /v SubscribedContent-338389Enabled /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager\" /v SubscribedContent-338393Enabled /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager\" /v SubscribedContent-353694Enabled /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager\" /v SubscribedContent-353696Enabled /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager\" /v SubscribedContent-88000326Enabled /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager\" /v SubscribedContentEnabled /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager\" /v SystemPaneSuggestionsEnabled /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\" /v EnableAutoTray /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced\" /v EnableSnapAssistFlyout /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced\" /v EnableSnapAssistFlyout /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced\" /v ShowCopilotButton /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced\" /v TaskbarDa /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced\" /v UseOLEDTaskbarTransparency /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced\" /v UseOLEDTaskbarTransparency /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced\\People\" /v PeopleBand /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Mobility\" /v OptedIn /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Notifications\\Settings\\Windows.SystemToast.Suggested\" /v Enabled /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer\" /v NoLowDiskSpaceChecks /t REG_DWORD /d 1 /f >nul 2>&1", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize\" /v ColorPrevalence /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize\" /v ColorPrevalence /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize\" /v EnableTransparency /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize\" /v EnableTransparency /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\UserProfileEngagement\" /v ScoobeSystemSettingEnabled /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\Software\\Policies\\Microsoft\\Windows\\Explorer\" /v DisableSearchBoxSuggestions /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\Software\\Policies\\Microsoft\\Windows\\WindowsAI\" /v DisableAIDataAnalysis /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKEY_CURRENT_USER\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsCopilot\" /v TurnOffWindowsCopilot /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced\" /v Hidden /t REG_DWORD /d 1 /f >nul 2>&1", "OTHER" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced\" /v HideFileExt /t REG_DWORD /d 0 /f >nul 2>&1", "OTHER" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced\" /v ShowSuperHidden /t REG_DWORD /d 1 /f >nul 2>&1", "OTHER" },
    { "reg add \"HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer\" /v AllowOnlineTips /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Edge\" /v ComposeInlineEnabled /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Edge\" /v DefaultBrowserSettingsCampaignEnabled /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\Explorer\" /v DisableSearchBoxSuggestions /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsAI\" /v DisableAIDataAnalysis /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsCopilot\" /v TurnOffWindowsCopilot /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\" /v SvcHostSplitThresholdInKB /t REG_DWORD /d 67108864 /f", "OTHER" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers\" /v \"DisableMultiplaneOverlay\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers\" /v \"HwSchMode\" /t REG_DWORD /d 2 /f", "OTHER" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers\" /v DisableMultiplaneOverlay /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\LanmanWorkstation\\Parameters\" /v DirectoryCacheLifetime /t REG_DWORD /d 0 /f >nul 2>&1", "OTHER" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\LanmanWorkstation\\Parameters\" /v FileInfoCacheLifetime /t REG_DWORD /d 0 /f >nul 2>&1", "OTHER" },
    { "reg add \"HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\LanmanWorkstation\\Parameters\" /v FileNotFoundCacheLifetime /t REG_DWORD /d 0 /f >nul 2>&1", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Microsoft\\PolicyManager\\current\\device\\System\" /v AllowExperimentation /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKLM\\Software\\Microsoft\\PolicyManager\\default\\WiFi\\AllowAutoConnectToWiFiSenseHotspots\" /v value /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKLM\\Software\\Microsoft\\PolicyManager\\default\\WiFi\\AllowWiFiHotSpotReporting\" /v value /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\MTCUVC\" /v EnableMtcUvc /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\DeliveryOptimization\\Config\" /v DODownloadMode /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Device Metadata\" /v PreventDeviceMetadataFromNetwork /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced\" /v UseOLEDTaskbarTransparency /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced\" /v UseOLEDTaskbarTransparency /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Desktop\\NameSpace\" /v B4FB3F98-C1EA-428d-A78A-D1F5659CBA93 /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\HideDesktopIcons\\NewStartPanel\" /v B4FB3F98-C1EA-428d-A78A-D1F5659CBA93 /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize\" /v AppsUseLightTheme /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize\" /v AppsUseLightTheme /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize\" /v SystemUsesLightTheme /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize\" /v SystemUsesLightTheme /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Microsoft\\Windows\\Windows Error Reporting\" /v Disabled /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Microsoft\\WindowsSelfHost\\UI\\Strings\" /v DiagnosticErrorText /t REG_SZ /d \"\" /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Microsoft\\WindowsSelfHost\\UI\\Strings\" /v DiagnosticLinkText /t REG_SZ /d \"\" /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Microsoft\\WindowsSelfHost\\UI\\Visibility\" /v DiagnosticErrorText /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKLM\\Software\\Policies\\Google\\Chrome\" /v CrashReportingEnabled /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKLM\\Software\\Policies\\Google\\Chrome\" /v CrashReportingEnabled /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKLM\\Software\\Policies\\Google\\Chrome\" /v MetricsReportingEnabled /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKLM\\Software\\Policies\\Google\\Chrome\" /v MetricsReportingEnabled /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Biometrics\" /v \"Enabled\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\PCHealth\\ErrorReporting\" /v DoReport /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Speech\" /v AllowSpeechModelUpdate /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\SQMClient\\Windows\" /v CEIPEnable /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppCompat\" /v AITEnable /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppCompat\" /v DisableEngine /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppCompat\" /v DisableInventory /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppCompat\" /v DisablePCA /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppCompat\" /v DisableUAR /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppCompat\" /v SbEnable /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\HomeGroup\" /v DisableHomeGroup /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\System\" /v PublishUserActivities /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Error Reporting\" /v Disabled /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search\" /v AllowCloudSearch /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search\" /v AllowCloudSearch /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search\" /v ConnectedSearchUseWeb /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search\" /v ConnectedSearchUseWeb /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search\" /v ConnectedSearchUseWebOverMeteredConnections /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search\" /v ConnectedSearchUseWebOverMeteredConnections /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search\" /v DisableWebSearch /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search\" /v DisableWebSearch /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU\" /v AUOptions /t REG_DWORD /d 2 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU\" /v NoAutoRebootWithLoggedOnUsers /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU\" /v NoAutoUpdate /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU\" /v NoAutoUpdate /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Wow6432Node\\Policies\\Microsoft\\Windows\\AppCompat\" /v DisableEngine /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Wow6432Node\\Policies\\Microsoft\\Windows\\AppCompat\" /v DisablePCA /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKLM\\SOFTWARE\\Wow6432Node\\Policies\\Microsoft\\Windows\\AppCompat\" /v SbEnable /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\Power\" /v \"HibernateEnabled\" /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\Power\\PowerThrottling\" /v PowerThrottlingOff /t REG_DWORD /d 1 /f", "OTHER" },
    { "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\AutoLogger\\SQMLogger\" /v Start /t REG_DWORD /d 0 /f", "OTHER" },
    { "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\DcpSvc\" /v Start /t REG_DWORD /d 4 /f", "OTHER" },
    { "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\dmwappushservice\" /v DelayedAutoStart /t REG_DWORD /d 1 /f > nul 2>&1", "OTHER" },
    { "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\dmwappushservice\" /v Start /t REG_DWORD /d 4 /f", "OTHER" },
    { "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\Fax\" /v Start /t REG_DWORD /d 3 /f", "OTHER" },
    { "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\Fax\" /v Start /t REG_DWORD /d 4 /f", "OTHER" },
    { "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\HomeGroupListener\" /v Start /t REG_DWORD /d 2 /f", "OTHER" },
    { "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\HomeGroupListener\" /v Start /t REG_DWORD /d 4 /f", "OTHER" },
    { "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\HomeGroupProvider\" /v Start /t REG_DWORD /d 2 /f", "OTHER" },
    { "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\HomeGroupProvider\" /v Start /t REG_DWORD /d 4 /f", "OTHER" },
    { "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\WbioSrvc\" /v \"Start\" /t REG_DWORD /d \"4\" /f", "OTHER" },
    { "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\wercplsupport\" /v Start /t REG_DWORD /d 3 /f", "OTHER" },
    { "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\wercplsupport\" /v Start /t REG_DWORD /d 4 /f", "OTHER" },
    { "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\WerSvc\" /v Start /t REG_DWORD /d 2 /f", "OTHER" },
    { "reg add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\WerSvc\" /v Start /t REG_DWORD /d 4 /f", "OTHER" },
    { "reg add \"HKU\\.DEFAULT\\Control Panel\\Mouse\" /v DoubleClickSpeed /t REG_SZ /d 0 /f", "OTHER" },
    { "reg add \"HKU\\.DEFAULT\\Control Panel\\Mouse\" /v MouseHoverTime /t REG_SZ /d 0 /f", "OTHER" },
    { "reg add \"HKU\\S-1-5-18\\Control Panel\\Mouse\" /v DoubleClickSpeed /t REG_SZ /d 0 /f", "OTHER" },
    { "reg add \"HKU\\S-1-5-18\\Control Panel\\Mouse\" /v MouseHoverTime /t REG_SZ /d 0 /f", "OTHER" },
    { "reg add \"HKU\\S-1-5-19\\Control Panel\\Mouse\" /v DoubleClickSpeed /t REG_SZ /d 0 /f", "OTHER" },
    { "reg add \"HKU\\S-1-5-19\\Control Panel\\Mouse\" /v MouseHoverTime /t REG_SZ /d 0 /f", "OTHER" },
    { "reg add \"HKU\\S-1-5-20\\Control Panel\\Mouse\" /v DoubleClickSpeed /t REG_SZ /d 0 /f", "OTHER" },
    { "reg add \"HKU\\S-1-5-20\\Control Panel\\Mouse\" /v MouseHoverTime /t REG_SZ /d 0 /f", "OTHER" },
    { "Reg.exe add \"HKCU\\SOFTWARE\\Microsoft\\Games\" /v \"FpsAll\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKCU\\SOFTWARE\\Microsoft\\Games\" /v \"FpsStatusGames\" /t REG_DWORD /d \"10\" /f", "OTHER" },
    { "Reg.exe add \"HKCU\\SOFTWARE\\Microsoft\\Games\" /v \"FpsStatusGamesAll\" /t REG_DWORD /d \"4\" /f", "OTHER" },
    { "Reg.exe add \"HKCU\\SOFTWARE\\Microsoft\\Games\" /v \"GameFluidity\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Office\\16.0\\Common\" /v \"qmEnable\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Office\\16.0\\Common\" /v \"sendcustomerdata\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Office\\16.0\\Common\" /v \"updatereliabilitydata\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Office\\16.0\\Common\\Feedback\" /v \"Enabled\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Office\\16.0\\Common\\Feedback\" /v \"includescreenshot\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Office\\16.0\\Common\\General\" /v \"shownfirstrunoptin\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Office\\16.0\\Common\\General\" /v \"skydrivesigninoption\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Office\\16.0\\Common\\ptwatson\" /v \"ptwoptin\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Office\\16.0\\Firstrun\" /v \"Disablemovie\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Office\\16.0\\OSM\" /v \"EnableFileObfuscation\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Office\\16.0\\OSM\" /v \"Enablelogging\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Office\\16.0\\OSM\" /v \"EnableUpload\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Office\\16.0\\OSM\\preventedapplications\" /v \"accesssolution\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Office\\16.0\\OSM\\preventedapplications\" /v \"olksolution\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Office\\16.0\\OSM\\preventedapplications\" /v \"onenotesolution\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Office\\16.0\\OSM\\preventedapplications\" /v \"pptsolution\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Office\\16.0\\OSM\\preventedapplications\" /v \"projectsolution\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Office\\16.0\\OSM\\preventedapplications\" /v \"publishersolution\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Office\\16.0\\OSM\\preventedapplications\" /v \"visiosolution\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Office\\16.0\\OSM\\preventedapplications\" /v \"wdsolution\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Office\\16.0\\OSM\\preventedapplications\" /v \"xlsolution\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Office\\16.0\\OSM\\preventedsolutiontypes\" /v \"agave\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Office\\16.0\\OSM\\preventedsolutiontypes\" /v \"appaddins\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Office\\16.0\\OSM\\preventedsolutiontypes\" /v \"comaddins\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Office\\16.0\\OSM\\preventedsolutiontypes\" /v \"documentfiles\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Office\\16.0\\OSM\\preventedsolutiontypes\" /v \"templatefiles\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Office\\16.0\\Outlook\\Options\\Mail\" /v \"EnableLogging\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKCU\\Software\\Microsoft\\Office\\16.0\\Word\\Options\" /v \"EnableLogging\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKEY_CURRENT_USER\\Control Panel\\International\\User Profile\" /v \"HttpAcceptLanguageOptOut\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Input\\TIPC\" /v \"Enabled\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Privacy\" /v \"TailoredExperiencesWithDiagnosticDataEnabled\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Attachments\" /v \"SaveZoneInformation\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKEY_LOCAL_MACHINE\\Software\\Policies\\Microsoft\\Windows\\System\" /v \"PublishUserActivities\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKEY_LOCAL_MACHINE\\Software\\Policies\\Microsoft\\Windows\\System\" /v \"UploadUserActivities\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Control\\Diagnostics\\Performance\" /v \"DisablediagnosticTracing\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Image File Execution Options\\csrss.exe\\PerfOptions\" /v \"CpuPriorityClass\" /t REG_DWORD /d \"4\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Image File Execution Options\\csrss.exe\\PerfOptions\" /v \"IoPriority\" /t REG_DWORD /d \"3\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\WUDF\" /v \"LogEnabling\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\WUDF\" /v \"LogLevel\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Reliability\" /v \"IoPriority\" /t REG_DWORD /d \"3\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Reliability\" /v \"TimeStampInterval\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Microsoft\\Windows\\Windows Error Reporting\" /v \"Disabled\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\PCHealth\\ErrorReporting\" /v \"DoReport\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\CloudContent\" /v \"DisableThirdPartySuggestions\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\CloudContent\" /v \"DisableWindowsConsumerFeatures\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Error Reporting\" /v \"Disabled\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Error Reporting\" /v \"DoReport\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Error Reporting\" /v \"LoggingDisabled\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search\" /v \"AllowCloudSearch\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search\" /v \"ConnectedSearchUseWeb\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search\" /v \"ConnectedSearchUseWebOverMeteredConnections\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search\" /v \"DisableWebSearch\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\" /v \"WaitToKillServiceTimeout\" /t REG_SZ /d \"1000\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers\\Power\" /v \"DefaultD3TransitionLatencyActivelyUsed\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers\\Power\" /v \"DefaultD3TransitionLatencyIdleLongTime\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers\\Power\" /v \"DefaultD3TransitionLatencyIdleMonitorOff\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers\\Power\" /v \"DefaultD3TransitionLatencyIdleNoContext\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers\\Power\" /v \"DefaultD3TransitionLatencyIdleShortTime\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers\\Power\" /v \"DefaultD3TransitionLatencyIdleVeryLongTime\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers\\Power\" /v \"DefaultLatencyToleranceIdle0\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers\\Power\" /v \"DefaultLatencyToleranceIdle0MonitorOff\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers\\Power\" /v \"DefaultLatencyToleranceIdle1\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers\\Power\" /v \"DefaultLatencyToleranceIdle1MonitorOff\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers\\Power\" /v \"DefaultLatencyToleranceMemory\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers\\Power\" /v \"DefaultLatencyToleranceNoContext\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers\\Power\" /v \"DefaultLatencyToleranceNoContextMonitorOff\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers\\Power\" /v \"DefaultLatencyToleranceOther\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers\\Power\" /v \"DefaultLatencyToleranceTimerPeriod\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers\\Power\" /v \"DefaultMemoryRefreshLatencyToleranceActivelyUsed\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers\\Power\" /v \"DefaultMemoryRefreshLatencyToleranceMonitorOff\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers\\Power\" /v \"DefaultMemoryRefreshLatencyToleranceNoContext\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers\\Power\" /v \"Latency\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers\\Power\" /v \"MaxIAverageGraphicsLatencyInOneBucket\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers\\Power\" /v \"MiracastPerfTrackGraphicsLatency\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers\\Power\" /v \"MonitorLatencyTolerance\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers\\Power\" /v \"MonitorRefreshLatencyTolerance\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers\\Power\" /v \"TransitionLatency\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa\\Credssp\" /v \"DebugLogLevel\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\Power\" /v \"ExitLatency\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\Power\" /v \"ExitLatencyCheckEnabled\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\Power\" /v \"Latency\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\Power\" /v \"LatencyToleranceDefault\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\Power\" /v \"LatencyToleranceFSVP\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\Power\" /v \"LatencyTolerancePerfOverride\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\Power\" /v \"LatencyToleranceScreenOffIR\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\Power\" /v \"LatencyToleranceVSyncEnabled\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\Power\" /v \"RtlCapabilityCheckLatency\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\AppModel\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\Cellcore\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\Circular Kernel Context Logger\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\CloudExperienceHostOobe\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\DataMarket\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\DiagLog\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\HolographicDevice\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\iclsClient\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\iclsProxy\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\LwtNetLog\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\Mellanox-Kernel\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\Microsoft-Windows-AssignedAccess-Trace\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\Microsoft-Windows-Setup\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\NBSMBLOGGER\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\PEAuthLog\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\RdrLog\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\ReadyBoot\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\SetupPlatform\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\SetupPlatformTel\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\SocketHeciServer\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\SpoolerLogger\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\SQMLogger\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\TileStore\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\Tpm\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\TPMProvisioningService\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\UBPM\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\WdiContextLog\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\WFP-IPsec Trace\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\WiFiDriverIHVSession\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\WiFiDriverIHVSessionRepro\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\WiFiSession\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\WinPhoneCritical\" /v \"Start\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Enum\\%%i\\Device Parameters\" /v \"AllowIdleIrpInD3\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Enum\\%%i\\Device Parameters\" /v \"D3ColdSupported\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Enum\\%%i\\Device Parameters\" /v \"DeviceSelectiveSuspended\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Enum\\%%i\\Device Parameters\" /v \"EnableSelectiveSuspend\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Enum\\%%i\\Device Parameters\" /v \"EnhancedPowerManagementEnabled\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Enum\\%%i\\Device Parameters\" /v \"SelectiveSuspendEnabled\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Enum\\%%i\\Device Parameters\" /v \"SelectiveSuspendOn\" /t REG_DWORD /d \"0\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\DXGKrnl\" /v \"MonitorLatencyTolerance\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\DXGKrnl\" /v \"MonitorRefreshLatencyTolerance\" /t REG_DWORD /d \"1\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\NDIS\\Parameters\" /v \"ThreadPriority\" /t REG_DWORD /d \"31\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\nvlddmkm\\Parameters\" /v \"ThreadPriority\" /t REG_DWORD /d \"31\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\USBHUB3\\Parameters\" /v \"ThreadPriority\" /t REG_DWORD /d \"31\" /f", "OTHER" },
    { "Reg.exe add \"HKLM\\SYSTEM\\CurrentControlSet\\Services\\usbxhci\\Parameters\" /v \"ThreadPriority\" /t REG_DWORD /d \"31\" /f", "OTHER" },
};
const int TWEAKS_OTHER_N = 302;


